name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
        sudo chown -R $USER:$USER /usr/local/lib/android/sdk
        curl -o sdk-tools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip sdk-tools-linux.zip -d /usr/local/lib/android/sdk/cmdline-tools/latest
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;27.0.12077973"
    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build app using Gradle
      run: ./gradlew assembleRelease
      env:
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Upload root APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: root
        path: app/build/outputs/apk/root/release/*.apk

    - name: Upload nonRoot APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nonRoot
        path: app/build/outputs/apk/nonRoot/release/*.apk
